import os
outfile = open('output.txt', 'w')
outfile.write('Old Folder Name,New Folder Name\n')
name_list = {"Associated Grocers of Florida, Inc":"Associated Grocers of Florida Inc","Access Display Group, Inc":"Access Display Group Inc","Anderson Merchandiser":"Anderson Merchandisers","Aramark Uniform Service":"Aramark Uniform Services","Access Businees Group - Vendorship":"Access Business Group - Vendorship","Access Business Group - Procurement":"Access Business Group Procurement","AM General, LLC":"AM General LLC","Arctic Zero, Inc":"Arctic Zero Inc","AT&T New Horizons":"ATT New Horizons","Alcatel-Lucent Technologies":"Alcatel Lucent Technologies","Arch Coal, Inc":"Arch Coal Inc","AutoAnything":"Auto Anything","ArchBrook Laguna LLC":"Archbrook Laguna LLC","Arrow-Speed Warehouse":"Arrow Speed Warehouse","Atwoods Distribution":"Atwoods Distributing","Avnet, Inc":"Avnet Inc","American Lafrance":"American LaFrance","American Signature Inc":"American Signature, Inc","AmeriSourceBergen":"AmerisourceBergen","Archer Daniels Midland Companies":"Archer Daniels Midland Company","Assa Abloy - Graham":"Assa Abloy Graham","Associated Food Stores DSD-XDock":"Associated Food Stores DSD Xdock","Associated Grocers of New England Inc":"Associated Grocers of New England","Associated Grocers of the South":"Associated Grocers of the South DSD","AutoZone":"Auto Zone","Advantage Sales & Marketing":"Advantage Sales and Marketing","All Star Dairy Association":"All Star Dairy Association Inc","Alliance Sales & Marketing":"Alliance Sales and Marketing","Armstrong Cabinet Products":"Armstrong Cabinet Products Inc","1800Contacts":"1 800 Contacts","Alliance Foods Inc":"Alliance Foods, Inc","Aldi United States of America":"ALDI United States of America","Applied Industrial Technologies":"Applied Industrial Technologies Canada","Arrow ECS Canada":"Arrow ECS Canada Ltd","Australian Pharmaceutical Industries":"Australian Pharmaceutical Ind","Automotive Distributor Network (thru Corecentric)":"Automotive Distribution Network Through Corcentric","Automotive Parts Headquarter":"Automotive Parts Headquarters, Inc.","Acklands Grainger Inc":"Acklands-Grainger","Armstrong Energy (OSR)":"Armstrong Energy","Axflow":"AxFlow","American Golf - OSR":"American Golf","Arrowhead Dental (OSR)":"Arrowhead Dental Lab","Associated Supply Company":"Associated Supply","Amerisourcebergen Canada":"Amerisourcebergen Canada Corporation","Afflink":"Afflink Inc","Anheuser Busch":"Anheuser Busch Company"}
#,"Altrec.com - OSR":"Altrec.com","Appleseed's":"Appleseed's, Inc","Altrec.com - OSR":"AltrecOSR"]
base = "EDI Guidelines"
for dir_name in os.walk(base).next()[1]:
    if dir_name in name_list.keys():
        new_name = name_list[dir_name]
        outfile.write(dir_name + ',' + new_name + '\n')
        os.rename(os.path.join(base, dir_name), os.path.join(base, new_name))
